services:
  postgres:
    image: postgres:17-alpine
    container_name: global_postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-edgar}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-123456}
      POSTGRES_DB: ${POSTGRES_DB:-juninhos}
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${POSTGRES_USER:-edgar}']
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - juninhos_network

volumes:
  postgres_data:

networks:
  juninhos_network:
    driver: bridge
